import type { HomePublicResponse } from "@/lib/types";
import { MOCK_ALL_SERVICES } from "@/lib/content/services";
import { MOCK_ALL_INDUSTRIES } from "@/lib/content/industries";

export const MOCK_HOME_DATA: HomePublicResponse = {
  hero: {
    id: "hero-1",
    eyebrow: "Products & Solutions",
    heading: "Empowering Innovation with AI & Cloud Solutions",
    description: "InfinityMind Tech delivers intelligent software solutions to accelerate your digital transformation across healthcare, retail, and modern enterprises.",
    primary_cta_text: "Explore Solutions",
    primary_cta_url: "/products",
    secondary_cta_text: "Our Services",
    secondary_cta_url: "/services",
    image: null,
    is_active: true,
    display_order: 1,
    updated_at: new Date().toISOString(),
  },
  popup: null,
  sections: [],
  featured_products: [
    {
      id: "prod-retail-billing",
      name: "Retail Billing",
      slug: "retail-billing",
      short_description: "Billing and finance software solution.",
      hero_image: null,
      category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
      is_active: true,
      is_featured: true,
      display_order: 1,
    },
    {
      id: "prod-cococraft",
      name: "CocoCraft",
      slug: "cococraft",
      short_description: "Business management software solution.",
      hero_image: null,
      category: { id: "cat-business", name: "Business Management", slug: "business-management", description: null, display_order: 2, is_active: true },
      is_active: true,
      is_featured: true,
      display_order: 2,
    },
    {
      id: "prod-crm",
      name: "CRM",
      slug: "crm",
      short_description: "Customer relationship management and ERP solution.",
      hero_image: null,
      category: { id: "cat-crm", name: "CRM & ERP", slug: "crm-erp", description: null, display_order: 3, is_active: true },
      is_active: true,
      is_featured: true,
      display_order: 3,
    },
    {
      id: "prod-restaurant",
      name: "Restaurant Management",
      slug: "restaurant-management",
      short_description: "Business management software solution.",
      hero_image: null,
      category: { id: "cat-business", name: "Business Management", slug: "business-management", description: null, display_order: 2, is_active: true },
      is_active: true,
      is_featured: true,
      display_order: 4,
    },
    {
      id: "prod-zenpayroll",
      name: "Zenpayroll",
      slug: "zenpayroll",
      short_description: "Billing and finance software solution.",
      hero_image: null,
      category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
      is_active: true,
      is_featured: true,
      display_order: 5,
    },
    {
      id: "prod-hotel",
      name: "Hotel Booking Management",
      slug: "hotel-booking-management",
      short_description: "Business management software solution.",
      hero_image: null,
      category: { id: "cat-business", name: "Business Management", slug: "business-management", description: null, display_order: 2, is_active: true },
      is_active: true,
      is_featured: true,
      display_order: 6,
    }
  ],
  services: MOCK_ALL_SERVICES,
  industries: MOCK_ALL_INDUSTRIES.filter(ind => ["healthcare", "banking-finance", "e-commerce", "manufacturing", "telecommunication", "education", "hospitality", "logistics"].includes(ind.slug)),
  about_preview: {
    eyebrow: "About Company",
    heading: "InfinityMind Tech Pvt. Ltd.",
    description: null,
    established_year: 2008,
    founder_name: "R. Jeyantha Senan, B.Tech, MBA",
    founder_title: "Founder / Chairman",
    cta_text: "Learn More About Us",
    cta_url: "/about",
  },
  final_cta: {
    headline: "Let’s Build Your Next Technology Solution",
    description: "Explore our technology services and solutions, or get in touch with InfinityMind Tech to discuss your requirements.",
    primary_cta_text: "Contact Us",
    primary_cta_url: "/contact",
    secondary_cta_text: "Explore Services",
    secondary_cta_url: "/services",
  },
};
