import type { IndustryListItem } from "@/lib/types";

export const MOCK_ALL_INDUSTRIES: IndustryListItem[] = [
  {
    id: "ind-healthcare",
    name: "Healthcare",
    slug: "healthcare",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 1,
  },
  {
    id: "ind-banking-finance",
    name: "Banking & Finance",
    slug: "banking-finance",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 2,
  },
  {
    id: "ind-e-commerce",
    name: "E-commerce",
    slug: "e-commerce",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 3,
  },
  {
    id: "ind-manufacturing",
    name: "Manufacturing",
    slug: "manufacturing",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 4,
  },
  {
    id: "ind-telecommunication",
    name: "Telecommunication",
    slug: "telecommunication",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 5,
  },
  {
    id: "ind-education",
    name: "Education",
    slug: "education",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 6,
  },
  {
    id: "ind-public-services",
    name: "Public Services",
    slug: "public-services",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 7,
  },
  {
    id: "ind-energy",
    name: "Energy",
    slug: "energy",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 8,
  },
  {
    id: "ind-hospitality",
    name: "Hospitality",
    slug: "hospitality",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 9,
  },
  {
    id: "ind-real-estate",
    name: "Real Estate",
    slug: "real-estate",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 10,
  },
  {
    id: "ind-autonomous-vehicle",
    name: "Autonomous Vehicle",
    slug: "autonomous-vehicle",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 11,
  },
  {
    id: "ind-logistics",
    name: "Logistics",
    slug: "logistics",
    short_description: null,
    image: null,
    is_active: true,
    display_order: 12,
  },
];
