import type { NavItem, FooterResponse, SocialLink } from "@/lib/types";

export const MOCK_NAV_ITEMS: NavItem[] = [
  {
    id: "nav-home",
    label: "Home",
    url: "/",
    parent_id: null,
    location: "header",
    display_order: 1,
    is_active: true,
    is_external: false,
    target: "_self",
    children: [],
  },
  {
    id: "nav-products",
    label: "Solutions",
    url: "/products",
    parent_id: null,
    location: "header",
    display_order: 2,
    is_active: true,
    is_external: false,
    target: "_self",
    children: [],
  },
  {
    id: "nav-services",
    label: "Services",
    url: "/services",
    parent_id: null,
    location: "header",
    display_order: 3,
    is_active: true,
    is_external: false,
    target: "_self",
    children: [],
  },
  {
    id: "nav-industries",
    label: "Industries",
    url: "/industries",
    parent_id: null,
    location: "header",
    display_order: 4,
    is_active: true,
    is_external: false,
    target: "_self",
    children: [],
  },
  {
    id: "nav-company",
    label: "Company",
    url: "#",
    parent_id: null,
    location: "header",
    display_order: 5,
    is_active: true,
    is_external: false,
    target: "_self",
    children: [
      {
        id: "nav-company-about",
        label: "About Us",
        url: "/about",
        parent_id: "nav-company",
        location: "header",
        display_order: 1,
        is_active: true,
        is_external: false,
        target: "_self",
        children: [],
      },
      {
        id: "nav-company-careers",
        label: "Careers",
        url: "/careers",
        parent_id: "nav-company",
        location: "header",
        display_order: 2,
        is_active: true,
        is_external: false,
        target: "_self",
        children: [],
      },
      {
        id: "nav-company-training",
        label: "Training",
        url: "/training",
        parent_id: "nav-company",
        location: "header",
        display_order: 3,
        is_active: true,
        is_external: false,
        target: "_self",
        children: [],
      },
    ],
  },
  {
    id: "nav-contact",
    label: "Contact",
    url: "/contact",
    parent_id: null,
    location: "header",
    display_order: 6,
    is_active: true,
    is_external: false,
    target: "_self",
    children: [],
  },
];

const MOCK_SOCIAL_LINKS: SocialLink[] = [
  { id: "s1", platform: "linkedin", url: "https://www.linkedin.com/company/infinitymind-tech/", icon: null, display_order: 1, is_active: true },
  { id: "s2", platform: "twitter", url: "#", icon: null, display_order: 2, is_active: true },
];

export const MOCK_FOOTER: FooterResponse = {
  nav_groups: {
    footer_products: [
      { id: "fp1", label: "All Solutions", url: "/products", parent_id: null, location: "footer_products", display_order: 1, is_active: true, is_external: false, target: "_self", children: [] },
    ],
    footer_services: [
      { id: "fs1", label: "All Services", url: "/services", parent_id: null, location: "footer_services", display_order: 1, is_active: true, is_external: false, target: "_self", children: [] },
    ],
    footer_industries: [
      { id: "fi1", label: "Healthcare", url: "/industries/healthcare", parent_id: null, location: "footer_industries", display_order: 1, is_active: true, is_external: false, target: "_self", children: [] },
      { id: "fi2", label: "Retail", url: "/industries/retail", parent_id: null, location: "footer_industries", display_order: 2, is_active: true, is_external: false, target: "_self", children: [] },
    ],
    footer_more: [
      { id: "fm1", label: "About Us", url: "/about", parent_id: null, location: "footer_more", display_order: 1, is_active: true, is_external: false, target: "_self", children: [] },
      { id: "fm2", label: "Careers", url: "/careers", parent_id: null, location: "footer_more", display_order: 2, is_active: true, is_external: false, target: "_self", children: [] },
      { id: "fm3", label: "Contact", url: "/contact", parent_id: null, location: "footer_more", display_order: 3, is_active: true, is_external: false, target: "_self", children: [] },
      { id: "fm4", label: "Privacy Policy", url: "/privacy-policy", parent_id: null, location: "footer_more", display_order: 4, is_active: true, is_external: false, target: "_self", children: [] },
      { id: "fm5", label: "Help Center", url: "/help", parent_id: null, location: "footer_more", display_order: 5, is_active: true, is_external: false, target: "_self", children: [] },
    ],
  },
  social_links: MOCK_SOCIAL_LINKS,
  description: "InfinityMind Tech Pvt Ltd offers innovative solutions in AI, Cloud Services, and Smart Tech for modern businesses.",
  copyright_text: "© 2026 InfinityMind Tech Pvt. Ltd. All rights reserved.",
};
