import type { ProductListItem } from "@/lib/types";

export const MOCK_ALL_PRODUCTS: ProductListItem[] = [
  {
    id: "prod-retail-billing",
    name: "Retail Billing",
    slug: "retail-billing",
    short_description: "Billing & Finance software solution.",
    hero_image: null,
    category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
    is_active: true,
    is_featured: true,
    display_order: 1,
  },
  {
    id: "prod-pos",
    name: "POS",
    slug: "pos",
    short_description: "Billing & Finance software solution.",
    hero_image: null,
    category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 2,
  },
  {
    id: "prod-vegetable-shop-billing",
    name: "Vegetable Shop Billing",
    slug: "vegetable-shop-billing",
    short_description: "Billing & Finance software solution.",
    hero_image: null,
    category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 3,
  },
  {
    id: "prod-cococraft",
    name: "CocoCraft",
    slug: "cococraft",
    short_description: "Business Management software solution.",
    hero_image: null,
    category: { id: "cat-business", name: "Business Management", slug: "business-management", description: null, display_order: 5, is_active: true },
    is_active: true,
    is_featured: true,
    display_order: 4,
  },
  {
    id: "prod-crm",
    name: "CRM",
    slug: "crm",
    short_description: "CRM & ERP software solution.",
    hero_image: null,
    category: { id: "cat-crm", name: "CRM & ERP", slug: "crm-erp", description: null, display_order: 2, is_active: true },
    is_active: true,
    is_featured: true,
    display_order: 5,
  },
  {
    id: "prod-stockgenius",
    name: "StockGenius",
    slug: "stockgenius",
    short_description: "CRM & ERP software solution.",
    hero_image: null,
    category: { id: "cat-crm", name: "CRM & ERP", slug: "crm-erp", description: null, display_order: 2, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 6,
  },
  {
    id: "prod-restaurant-management",
    name: "Restaurant Management",
    slug: "restaurant-management",
    short_description: "Business Management software solution.",
    hero_image: null,
    category: { id: "cat-business", name: "Business Management", slug: "business-management", description: null, display_order: 5, is_active: true },
    is_active: true,
    is_featured: true,
    display_order: 7,
  },
  {
    id: "prod-goldflow",
    name: "GoldFlow",
    slug: "goldflow",
    short_description: "Billing & Finance software solution.",
    hero_image: null,
    category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 8,
  },
  {
    id: "prod-controllq",
    name: "ControllQ",
    slug: "controllq",
    short_description: "IoT & Monitoring software solution.",
    hero_image: null,
    category: { id: "cat-iot", name: "IoT & Monitoring", slug: "iot-monitoring", description: null, display_order: 4, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 9,
  },
  {
    id: "prod-presencepro",
    name: "PresencePro",
    slug: "presencepro",
    short_description: "IoT & Monitoring software solution.",
    hero_image: null,
    category: { id: "cat-iot", name: "IoT & Monitoring", slug: "iot-monitoring", description: null, display_order: 4, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 10,
  },
  {
    id: "prod-zenpayroll",
    name: "Zenpayroll",
    slug: "zenpayroll",
    short_description: "Billing & Finance software solution.",
    hero_image: null,
    category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
    is_active: true,
    is_featured: true,
    display_order: 11,
  },
  {
    id: "prod-hotel-booking-management",
    name: "Hotel Booking Management",
    slug: "hotel-booking-management",
    short_description: "Business Management software solution.",
    hero_image: null,
    category: { id: "cat-business", name: "Business Management", slug: "business-management", description: null, display_order: 5, is_active: true },
    is_active: true,
    is_featured: true,
    display_order: 12,
  },
  {
    id: "prod-weave-xpert",
    name: "Weave Xpert",
    slug: "weave-xpert",
    short_description: "Business Management software solution.",
    hero_image: null,
    category: { id: "cat-business", name: "Business Management", slug: "business-management", description: null, display_order: 5, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 13,
  },
  {
    id: "prod-static-web-designing",
    name: "Static Web Designing",
    slug: "static-web-designing",
    short_description: "Web Designing Solutions software solution.",
    hero_image: null,
    category: { id: "cat-web", name: "Web Designing Solutions", slug: "web-designing-solutions", description: null, display_order: 3, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 14,
  },
  {
    id: "prod-dynamic-web-designing",
    name: "Dynamic Web Designing",
    slug: "dynamic-web-designing",
    short_description: "Web Designing Solutions software solution.",
    hero_image: null,
    category: { id: "cat-web", name: "Web Designing Solutions", slug: "web-designing-solutions", description: null, display_order: 3, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 15,
  },
  {
    id: "prod-b2b-web-designing",
    name: "B2B Web Designing",
    slug: "b2b-web-designing",
    short_description: "Web Designing Solutions software solution.",
    hero_image: null,
    category: { id: "cat-web", name: "Web Designing Solutions", slug: "web-designing-solutions", description: null, display_order: 3, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 16,
  },
  {
    id: "prod-ecommerce-web-designing",
    name: "Ecommerce Web Designing",
    slug: "ecommerce-web-designing",
    short_description: "Web Designing Solutions software solution.",
    hero_image: null,
    category: { id: "cat-web", name: "Web Designing Solutions", slug: "web-designing-solutions", description: null, display_order: 3, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 17,
  },
  {
    id: "prod-matrimonial-web-designing",
    name: "Matrimonial Web Designing",
    slug: "matrimonial-web-designing",
    short_description: "Web Designing Solutions software solution.",
    hero_image: null,
    category: { id: "cat-web", name: "Web Designing Solutions", slug: "web-designing-solutions", description: null, display_order: 3, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 18,
  },
  {
    id: "prod-job-web-designing",
    name: "Job Web Designing",
    slug: "job-web-designing",
    short_description: "Web Designing Solutions software solution.",
    hero_image: null,
    category: { id: "cat-web", name: "Web Designing Solutions", slug: "web-designing-solutions", description: null, display_order: 3, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 19,
  },
  {
    id: "prod-swiftdeliver",
    name: "SwiftDeliver",
    slug: "swiftdeliver",
    short_description: "Business Management software solution.",
    hero_image: null,
    category: { id: "cat-business", name: "Business Management", slug: "business-management", description: null, display_order: 5, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 20,
  },
  {
    id: "prod-academixpro",
    name: "AcademixPro",
    slug: "academixpro",
    short_description: "CRM & ERP software solution.",
    hero_image: null,
    category: { id: "cat-crm", name: "CRM & ERP", slug: "crm-erp", description: null, display_order: 2, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 21,
  },
  {
    id: "prod-turbobill",
    name: "TurboBill",
    slug: "turbobill",
    short_description: "Billing & Finance software solution.",
    hero_image: null,
    category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 22,
  },
  {
    id: "prod-automobile-service-billing",
    name: "Automobile Service Billing",
    slug: "automobile-service-billing",
    short_description: "Billing & Finance software solution.",
    hero_image: null,
    category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 23,
  },
  {
    id: "prod-fin-ease",
    name: "Fin Ease",
    slug: "fin-ease",
    short_description: "Billing & Finance software solution.",
    hero_image: null,
    category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 24,
  },
  {
    id: "prod-warehouse-management",
    name: "Warehouse Management",
    slug: "warehouse-management",
    short_description: "CRM & ERP software solution.",
    hero_image: null,
    category: { id: "cat-crm", name: "CRM & ERP", slug: "crm-erp", description: null, display_order: 2, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 25,
  },
  {
    id: "prod-door-sense",
    name: "Door Sense",
    slug: "door-sense",
    short_description: "IoT & Monitoring software solution.",
    hero_image: null,
    category: { id: "cat-iot", name: "IoT & Monitoring", slug: "iot-monitoring", description: null, display_order: 4, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 26,
  },
  {
    id: "prod-rent-ease",
    name: "Rent Ease",
    slug: "rent-ease",
    short_description: "Business Management software solution.",
    hero_image: null,
    category: { id: "cat-business", name: "Business Management", slug: "business-management", description: null, display_order: 5, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 27,
  },
  {
    id: "prod-feathertrack",
    name: "FeatherTrack",
    slug: "feathertrack",
    short_description: "Business Management software solution.",
    hero_image: null,
    category: { id: "cat-business", name: "Business Management", slug: "business-management", description: null, display_order: 5, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 28,
  },
  {
    id: "prod-billgenius",
    name: "BillGenius",
    slug: "billgenius",
    short_description: "Billing & Finance software solution.",
    hero_image: null,
    category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
    is_active: true,
    is_featured: true,
    display_order: 29,
  },
  {
    id: "prod-gold-loan-management",
    name: "Gold Loan Management",
    slug: "gold-loan-management",
    short_description: "Billing & Finance software solution.",
    hero_image: null,
    category: { id: "cat-billing", name: "Billing & Finance", slug: "billing-finance", description: null, display_order: 1, is_active: true },
    is_active: true,
    is_featured: false,
    display_order: 30,
  },
];
