import type { ServiceListItem } from "@/lib/types";

export const MOCK_ALL_SERVICES: ServiceListItem[] = [
  {
    id: "srv-mobile",
    name: "Mobile App Development",
    slug: "mobile-app-development",
    short_description: null,
    icon: "Smartphone",
    image: null,
    is_active: true,
    is_featured: true,
    display_order: 1,
  },
  {
    id: "srv-consulting",
    name: "Consulting",
    slug: "consulting",
    short_description: null,
    icon: "Briefcase",
    image: null,
    is_active: true,
    is_featured: true,
    display_order: 2,
  },
  {
    id: "srv-data",
    name: "Data Analytics",
    slug: "data-analytics",
    short_description: null,
    icon: "BarChart",
    image: null,
    is_active: true,
    is_featured: true,
    display_order: 3,
  },
  {
    id: "srv-digital",
    name: "Digital Marketing",
    slug: "digital-marketing",
    short_description: null,
    icon: "Megaphone",
    image: null,
    is_active: true,
    is_featured: true,
    display_order: 4,
  },
  {
    id: "srv-ecommerce",
    name: "E-commerce",
    slug: "e-commerce",
    short_description: null,
    icon: "ShoppingCart",
    image: null,
    is_active: true,
    is_featured: true,
    display_order: 5,
  },
  {
    id: "srv-ai",
    name: "Artificial Intelligence",
    slug: "artificial-intelligence",
    short_description: null,
    icon: "Brain",
    image: null,
    is_active: true,
    is_featured: true,
    display_order: 6,
  },
  {
    id: "srv-network",
    name: "Network Services",
    slug: "network-services",
    short_description: null,
    icon: "Network",
    image: null,
    is_active: true,
    is_featured: false,
    display_order: 7,
  },
  {
    id: "srv-blockchain",
    name: "Blockchain",
    slug: "blockchain",
    short_description: null,
    icon: "Link",
    image: null,
    is_active: true,
    is_featured: false,
    display_order: 8,
  },
];
