import type { TrainingDetail } from "@/lib/types";

export const MOCK_TRAINING_PROGRAMS: TrainingDetail[] = [
  {
    id: "tp-java-full-stack",
    name: "Java Full Stack",
    slug: "java-full-stack",
    short_description: "Master frontend (React, Angular) & backend (Spring Boot, Hibernate).",
    description: null,
    image: null,
    duration: null,
    is_active: true,
    display_order: 1,
    features: [],
    who_can_apply: ["Final Year Students", "Recent Graduates", "Anyone Passionate About Learning — No Experience Needed!"],
    what_you_gain: ["Industry-Relevant Skillset", "Internship Certificate", "Live Project Experience", "Mentorship From Industry Experts", "Placement Assistance"],
    cta_text: null,
    cta_url: null,
    meta_title: null,
    meta_description: null,
  },
  {
    id: "tp-big-data",
    name: "Big Data — Full Stack",
    slug: "big-data-full-stack",
    short_description: "Master Hadoop, Spark, Scala, Python, and cloud tools for end-to-end data engineering.",
    description: null,
    image: null,
    duration: null,
    is_active: true,
    display_order: 2,
    features: [],
    who_can_apply: ["Final Year Students", "Recent Graduates", "Anyone Passionate About Learning — No Experience Needed!"],
    what_you_gain: ["Industry-Relevant Skillset", "Internship Certificate", "Live Project Experience", "Mentorship From Industry Experts", "Placement Assistance"],
    cta_text: null,
    cta_url: null,
    meta_title: null,
    meta_description: null,
  },
  {
    id: "tp-php",
    name: "PHP — Full Stack",
    slug: "php-full-stack",
    short_description: "From core PHP to Laravel framework with MySQL and frontend technologies.",
    description: null,
    image: null,
    duration: null,
    is_active: true,
    display_order: 3,
    features: [],
    who_can_apply: ["Final Year Students", "Recent Graduates", "Anyone Passionate About Learning — No Experience Needed!"],
    what_you_gain: ["Industry-Relevant Skillset", "Internship Certificate", "Live Project Experience", "Mentorship From Industry Experts", "Placement Assistance"],
    cta_text: null,
    cta_url: null,
    meta_title: null,
    meta_description: null,
  },
  {
    id: "tp-ibm-mainframe",
    name: "IBM Mainframe",
    slug: "ibm-mainframe",
    short_description: "Ideal for careers in banking, finance, insurance, and government sectors.",
    description: null,
    image: null,
    duration: null,
    is_active: true,
    display_order: 4,
    features: [],
    who_can_apply: ["Final Year Students", "Recent Graduates", "Anyone Passionate About Learning — No Experience Needed!"],
    what_you_gain: ["Industry-Relevant Skillset", "Internship Certificate", "Live Project Experience", "Mentorship From Industry Experts", "Placement Assistance"],
    cta_text: null,
    cta_url: null,
    meta_title: null,
    meta_description: null,
  },
  {
    id: "tp-digital-marketing",
    name: "Digital Marketing",
    slug: "digital-marketing",
    short_description: "SEO, SEM, Social Media, Google Ads, Canva, WordPress & more.",
    description: null,
    image: null,
    duration: null,
    is_active: true,
    display_order: 5,
    features: [],
    who_can_apply: ["Final Year Students", "Recent Graduates", "Anyone Passionate About Learning — No Experience Needed!"],
    what_you_gain: ["Industry-Relevant Skillset", "Internship Certificate", "Live Project Experience", "Mentorship From Industry Experts", "Placement Assistance"],
    cta_text: null,
    cta_url: null,
    meta_title: null,
    meta_description: null,
  },
  {
    id: "tp-android-ios",
    name: "Android & iOS App Development",
    slug: "android-ios-app-development",
    short_description: "Build mobile apps using Kotlin, Java (Android) and Swift (iOS). Includes UI/UX.",
    description: null,
    image: null,
    duration: null,
    is_active: true,
    display_order: 6,
    features: [],
    who_can_apply: ["Final Year Students", "Recent Graduates", "Anyone Passionate About Learning — No Experience Needed!"],
    what_you_gain: ["Industry-Relevant Skillset", "Internship Certificate", "Live Project Experience", "Mentorship From Industry Experts", "Placement Assistance"],
    cta_text: null,
    cta_url: null,
    meta_title: null,
    meta_description: null,
  }
];
